# Generated by Django 3.0.8 on 2020-07-22 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=20)),
                ('CommentId', models.CharField(max_length=20)),
                ('CommentTitle', models.CharField(max_length=100)),
                ('CommentTime', models.CharField(max_length=100)),
                ('CommentDate', models.CharField(max_length=100)),
                ('Comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=20)),
                ('PostId', models.CharField(max_length=20)),
                ('PostTitle', models.CharField(max_length=100)),
                ('PostTime', models.CharField(max_length=100)),
                ('PostDate', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpeg', upload_to='statics/images/Post_images')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=20)),
                ('prod_image', models.ImageField(default='default.jpeg', upload_to='statics/images/project_images')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=20)),
                ('ReplyId', models.CharField(max_length=20)),
                ('ReplyTitle', models.CharField(max_length=100)),
                ('CommentId', models.CharField(max_length=100)),
                ('ReplyDate', models.CharField(max_length=100)),
                ('Reply', models.CharField(max_length=100)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myweb.Comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myweb.Post'),
        ),
    ]
