# Generated by Django 3.0.8 on 2020-07-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='title',
            new_name='Services_title',
        ),
    ]
