# Generated by Django 3.0.8 on 2020-07-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_auto_20200722_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='prod_image',
            field=models.ImageField(default='default.jpeg', upload_to='statics/images/Services_images'),
        ),
    ]
