# Generated by Django 3.0.8 on 2020-07-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_auto_20200722_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='prod_image',
            new_name='serv_image',
        ),
    ]
