# Generated by Django 3.0.8 on 2020-07-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0006_auto_20200722_1704'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
